from glob import glob
import cv2
import numpy as np
import sys

def load_sprites():
    sprite_paths = [
        "sprites/SuperMarioBros-Nes/1.png",
        "sprites/SuperMarioBros-Nes/2.png",
        "sprites/SuperMarioBros-Nes/3.png",
        "sprites/SuperMarioBros-Nes/4.png",
        "sprites/SuperMarioBros-Nes/5.png",
        "sprites/SuperMarioBros-Nes/6.png",
        "sprites/SuperMarioBros-Nes/7.png",
        "sprites/SuperMarioBros-Nes/8.png",
        "sprites/SuperMarioBros-Nes/9.png",
        "sprites/SuperMarioBros-Nes/A.png",
        "sprites/SuperMarioBros-Nes/block_coin_1.png",
        "sprites/SuperMarioBros-Nes/block_coin_2.png",
        "sprites/SuperMarioBros-Nes/block_coin_3.png",
        "sprites/SuperMarioBros-Nes/block_coin_4.png",
        "sprites/SuperMarioBros-Nes/block.png",
        "sprites/SuperMarioBros-Nes/bricks_debris.png",
        "sprites/SuperMarioBros-Nes/bricks.png",
        "sprites/SuperMarioBros-Nes/bush_1.png",
        "sprites/SuperMarioBros-Nes/bush_2.png",
        "sprites/SuperMarioBros-Nes/bush_3.png",
        "sprites/SuperMarioBros-Nes/bush_4.png",
        "sprites/SuperMarioBros-Nes/cloud_1.png",
        "sprites/SuperMarioBros-Nes/cloud_2.png",
        "sprites/SuperMarioBros-Nes/cloud_3.png",
        "sprites/SuperMarioBros-Nes/D.png",
        "sprites/SuperMarioBros-Nes/E.png",
        "sprites/SuperMarioBros-Nes/fireball_1.png",
        "sprites/SuperMarioBros-Nes/fireball_2.png",
        "sprites/SuperMarioBros-Nes/fireball_3.png",
        "sprites/SuperMarioBros-Nes/fireball_4.png",
        "sprites/SuperMarioBros-Nes/fireball_explosion_1.png",
        "sprites/SuperMarioBros-Nes/fireball_explosion_2.png",
        "sprites/SuperMarioBros-Nes/fireball_explosion_3.png",
        "sprites/SuperMarioBros-Nes/fireball_explosion_4.png",
        "sprites/SuperMarioBros-Nes/fire_flower_1.png",
        "sprites/SuperMarioBros-Nes/fire_flower_2.png",
        "sprites/SuperMarioBros-Nes/fire_flower_3.png",
        "sprites/SuperMarioBros-Nes/fire_flower_4.png",
        "sprites/SuperMarioBros-Nes/goal_flag.png",
        "sprites/SuperMarioBros-Nes/goomba_1.png",
        "sprites/SuperMarioBros-Nes/goomba_2.png",
        "sprites/SuperMarioBros-Nes/goomba_squashed.png",
        "sprites/SuperMarioBros-Nes/ground.png",
        "sprites/SuperMarioBros-Nes/I.png",
        "sprites/SuperMarioBros-Nes/koopa.png",
        "sprites/SuperMarioBros-Nes/koopa_shell.png",
        "sprites/SuperMarioBros-Nes/little_1.png",
        "sprites/SuperMarioBros-Nes/little_2.png",
        "sprites/SuperMarioBros-Nes/little_4.png",
        "sprites/SuperMarioBros-Nes/little_5.png",
        "sprites/SuperMarioBros-Nes/little_8.png",
        "sprites/SuperMarioBros-Nes/little_coin_1.png",
        "sprites/SuperMarioBros-Nes/little_coin_2.png",
        "sprites/SuperMarioBros-Nes/little_coin_3.png",
        "sprites/SuperMarioBros-Nes/little_x.png",
        "sprites/SuperMarioBros-Nes/little_zero.png",
        "sprites/SuperMarioBros-Nes/L.png",
        "sprites/SuperMarioBros-Nes/M.png",
        "sprites/SuperMarioBros-Nes/mushroom.png",
        "sprites/SuperMarioBros-Nes/O.png",
        "sprites/SuperMarioBros-Nes/pipe.png",
        "sprites/SuperMarioBros-Nes/pipe_top.png",
        "sprites/SuperMarioBros-Nes/qblock_1.png",
        "sprites/SuperMarioBros-Nes/qblock_2.png",
        "sprites/SuperMarioBros-Nes/qblock_3.png",
        "sprites/SuperMarioBros-Nes/qblock_spent.png",
        "sprites/SuperMarioBros-Nes/R.png",
        "sprites/SuperMarioBros-Nes/T.png",
        "sprites/SuperMarioBros-Nes/victory_flag.png",
        "sprites/SuperMarioBros-Nes/W.png",
        "sprites/SuperMarioBros-Nes/Zero.png",
    ]


    for i in sprite_paths:
        sprite = cv2.imread(i)
        cv2.imwrite(i, sprite[::2,::2])

load_sprites()
